# This rule is not used by the project kube-guard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ops.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-guard
    app.kubernetes.io/managed-by: kustomize
  name: guardpolicy-admin-role
rules:
- apiGroups:
  - ops.example.com
  resources:
  - guardpolicies
  verbs:
  - '*'
- apiGroups:
  - ops.example.com
  resources:
  - guardpolicies/status
  verbs:
  - get
